name: LpkAutoSell
main: LamPocketVN\AutoSell\main
version: 0.0.1
api: [3.0.0, 3.9.0, 4.0.0]
author: LamPocketVN
description: sell all your items
commands:
  as:
    description: "Sells the item in your hand or all of your inventory's contents"
    permission: lpkas.command
permissions:
  lpkas.command:
    default: true
